using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents;

public abstract class PartyComponent
{
	public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);

	public MobileParty MobileParty { get; private set; }

	public PartyBase Party => MobileParty.Party;

	public abstract Hero PartyOwner { get; }

	public abstract TextObject Name { get; }

	public abstract Settlement HomeSettlement { get; }

	public virtual bool AvoidHostileActions => false;

	public virtual int WagePaymentLimit => Campaign.Current.Models.PartyWageModel.MaxWage;

	public virtual Hero Leader => null;

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
	}

	public virtual void SetWagePaymentLimit(int newLimit)
	{
		Debug.FailedAssert("Invalid set wage payment limit function usage!", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "SetWagePaymentLimit", 28);
	}

	internal void SetMobilePartyInternal(MobileParty party)
	{
		MobileParty = party;
	}

	internal void Initialize(MobileParty party)
	{
		SetMobilePartyInternal(party);
		OnInitialize();
	}

	internal void Finish()
	{
		OnFinalize();
	}

	protected virtual void OnInitialize()
	{
	}

	protected virtual void OnFinalize()
	{
	}

	public virtual void ClearCachedName()
	{
	}

	public virtual void ChangePartyLeader(Hero newLeader)
	{
	}

	public virtual void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
	{
		mountStringId = "";
		harnessStringId = "";
	}
}
You are not using the latest version of the tool, please update.
Latest version is '10.1.1.8388' (yours is '8.2.0.7535-95108c96')
