using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem;

public class FactionManager
{
	[SaveableField(20)]
	private FactionManagerStancesData _stances;

	public static FactionManager Instance => Campaign.Current.FactionManager;

	internal static void AutoGeneratedStaticCollectObjectsFactionManager(object o, List<object> collectedObjects)
	{
		((FactionManager)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(_stances);
	}

	internal static object AutoGeneratedGetMemberValue_stances(object o)
	{
		return ((FactionManager)o)._stances;
	}

	public FactionManager()
	{
		_stances = new FactionManagerStancesData();
	}

	internal void PreAfterLoad()
	{
		if (MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.3.0"))
		{
			List<StanceLink> list = new List<StanceLink>();
			foreach (StanceLink stanceLink in _stances.GetStanceLinks())
			{
				if (Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(stanceLink.Faction1, stanceLink.Faction2).HasValue)
				{
					list.Add(stanceLink);
				}
			}
			foreach (StanceLink item in list)
			{
				_stances.RemoveStance(item);
			}
		}
		foreach (StanceLink item2 in _stances.GetStanceLinks().ToList())
		{
			if (item2.Faction1 != item2.Faction2 && (item2.Faction1.IsEliminated || item2.Faction2.IsEliminated))
			{
				RemoveStance(item2);
			}
		}
	}

	internal void AfterLoad()
	{
		if (!MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.2.9.35637")))
		{
			return;
		}
		foreach (StanceLink stanceLink in _stances.GetStanceLinks())
		{
			if (Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(stanceLink.Faction1, stanceLink.Faction2) && !stanceLink.IsAtWar)
			{
				stanceLink.StanceType = StanceType.War;
			}
		}
	}

	internal StanceLink GetStanceLinkInternal(IFaction faction1, IFaction faction2)
	{
		StanceLink stanceLink = _stances.GetStance(faction1, faction2);
		if (stanceLink == null)
		{
			stanceLink = new StanceLink((Campaign.Current.Models.DiplomacyModel.GetDefaultDiplomaticStance(faction1, faction2) == DiplomacyModel.DiplomacyStance.War) ? StanceType.War : StanceType.Neutral, faction1, faction2);
			AddStance(faction1, faction2, stanceLink);
		}
		return stanceLink;
	}

	private void AddStance(IFaction faction1, IFaction faction2, StanceLink stanceLink)
	{
		if (!faction1.IsEliminated && !faction2.IsEliminated && !Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(faction1, faction2).HasValue)
		{
			_stances.AddStance(stanceLink);
			if (stanceLink.IsAtWar && !Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(faction1, faction2))
			{
				faction1.UpdateFactionsAtWarWith();
				faction2.UpdateFactionsAtWarWith();
			}
		}
	}

	private void RemoveStance(StanceLink stance)
	{
		_stances.RemoveStance(stance);
	}

	private static void SetStance(IFaction faction1, IFaction faction2, StanceType stanceType)
	{
		StanceLink stanceLinkInternal = Instance.GetStanceLinkInternal(faction1, faction2);
		StanceType stanceType2 = stanceLinkInternal.StanceType;
		stanceLinkInternal.StanceType = stanceType;
		if (stanceType2 == StanceType.War || stanceType == StanceType.War)
		{
			faction1.UpdateFactionsAtWarWith();
			faction2.UpdateFactionsAtWarWith();
		}
	}

	public static void DeclareWar(IFaction faction1, IFaction faction2)
	{
		DiplomacyModel.DiplomacyStance? shallowDiplomaticStance = Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(faction1, faction2);
		if (faction1 != faction2 && !shallowDiplomaticStance.HasValue)
		{
			SetStance(faction1, faction2, StanceType.War);
		}
	}

	public static void SetNeutral(IFaction faction1, IFaction faction2)
	{
		DiplomacyModel.DiplomacyStance? shallowDiplomaticStance = Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(faction1, faction2);
		if (faction1 != faction2 && !shallowDiplomaticStance.HasValue)
		{
			StanceLink stanceLinkInternal = Instance.GetStanceLinkInternal(faction1, faction2);
			StanceType stanceType = stanceLinkInternal.StanceType;
			stanceLinkInternal.StanceType = StanceType.Neutral;
			if (stanceType == StanceType.War)
			{
				faction1.UpdateFactionsAtWarWith();
				faction2.UpdateFactionsAtWarWith();
			}
		}
	}

	public static bool IsAtWarAgainstFaction(IFaction faction1, IFaction faction2)
	{
		if (faction1 == null || faction2 == null || faction1 == faction2 || faction1.IsEliminated || faction2.IsEliminated)
		{
			return false;
		}
		if (Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(faction1, faction2))
		{
			return true;
		}
		DiplomacyModel.DiplomacyStance? shallowDiplomaticStance = Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(faction1, faction2);
		if (shallowDiplomaticStance.HasValue)
		{
			return shallowDiplomaticStance == DiplomacyModel.DiplomacyStance.War;
		}
		return Instance.GetStanceLinkInternal(faction1, faction2).IsAtWar;
	}

	public static bool IsAtConstantWarAgainstFaction(IFaction faction1, IFaction faction2)
	{
		if (faction1 == null || faction2 == null || faction1 == faction2 || faction1.IsEliminated || faction2.IsEliminated)
		{
			return false;
		}
		return Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(faction1, faction2);
	}

	public static bool IsNeutralWithFaction(IFaction faction1, IFaction faction2)
	{
		if (faction1 == null || faction2 == null || faction1 == faction2 || faction1.IsEliminated || faction2.IsEliminated || Campaign.Current.Models.DiplomacyModel.IsAtConstantWar(faction1, faction2))
		{
			return false;
		}
		DiplomacyModel.DiplomacyStance? shallowDiplomaticStance = Campaign.Current.Models.DiplomacyModel.GetShallowDiplomaticStance(faction1, faction2);
		if (shallowDiplomaticStance.HasValue)
		{
			return shallowDiplomaticStance == DiplomacyModel.DiplomacyStance.Neutral;
		}
		StanceLink stanceLinkInternal = Instance.GetStanceLinkInternal(faction1, faction2);
		if (stanceLinkInternal == null && ((faction1.IsBanditFaction && !faction2.IsBanditFaction && !faction2.IsOutlaw) || (faction2.IsBanditFaction && !faction1.IsBanditFaction && !faction1.IsOutlaw)))
		{
			return false;
		}
		return stanceLinkInternal?.IsNeutral ?? true;
	}

	internal void RemoveFactionsFromCampaignWars(IFaction faction1)
	{
		if (faction1.MapFaction != faction1)
		{
			return;
		}
		StanceLink[] array = (from x in _stances.GetStanceLinks()
			where x.Faction1 == faction1 || x.Faction2 == faction1
			select x).ToArray();
		foreach (StanceLink stance in array)
		{
			RemoveStance(stance);
		}
		foreach (IFaction item in faction1.FactionsAtWarWith)
		{
			item.UpdateFactionsAtWarWith();
		}
		faction1.UpdateFactionsAtWarWith();
	}

	public static int GetRelationBetweenClans(Clan clan1, Clan clan2)
	{
		float num = 0f;
		float num2 = 1E-05f;
		if ((clan1.AliveLords.Count == 0 && clan1.IsBanditFaction && !clan2.IsBanditFaction) || (clan2.AliveLords.Count == 0 && clan2.IsBanditFaction && !clan1.IsBanditFaction))
		{
			return -10;
		}
		foreach (Hero aliveLord in clan1.AliveLords)
		{
			if (!(aliveLord.Age > (float)Campaign.Current.Models.AgeModel.HeroComesOfAge))
			{
				continue;
			}
			foreach (Hero aliveLord2 in clan2.AliveLords)
			{
				if (aliveLord2.Age > (float)Campaign.Current.Models.AgeModel.HeroComesOfAge)
				{
					float num3 = 0.1f;
					if (aliveLord == clan1.Leader)
					{
						num3 += 0.2f;
					}
					else if (aliveLord == clan1.Leader?.Spouse)
					{
						num3 += 0.05f;
					}
					if (aliveLord2 == clan2.Leader)
					{
						num3 += 0.2f;
					}
					else if (aliveLord2 == clan2.Leader?.Spouse)
					{
						num3 += 0.05f;
					}
					if (aliveLord == clan1.Leader && aliveLord2 == clan2.Leader)
					{
						num3 *= 20f;
					}
					int baseHeroRelation = aliveLord.GetBaseHeroRelation(aliveLord2);
					num += num3 * (float)baseHeroRelation;
					num2 += num3;
				}
			}
		}
		return (int)(num / num2);
	}
}
You are not using the latest version of the tool, please update.
Latest version is '11.0.0.9375' (yours is '8.2.0.7535-95108c96')
