using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents;

public abstract class PartyComponent
{
	public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);

	public MobileParty MobileParty { get; private set; }

	public PartyBase Party => MobileParty.Party;

	public abstract Hero PartyOwner { get; }

	public abstract TextObject Name { get; }

	public abstract Settlement HomeSettlement { get; }

	public virtual bool AvoidHostileActions => false;

	public virtual int WagePaymentLimit => Campaign.Current.Models.PartyWageModel.MaxWagePaymentLimit;

	public virtual Hero Leader => null;

	public Banner Banner => MobileParty.Banner;

	public virtual bool CanHaveNavalNavigationCapability => MobileParty.ActualClan?.HasNavalNavigationCapability ?? false;

	public virtual bool CanHaveLandNavigationCapability => true;

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
	}

	public virtual void SetWagePaymentLimit(int newLimit)
	{
		Debug.FailedAssert("Invalid set wage payment limit function usage!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "SetWagePaymentLimit", 30);
	}

	public abstract Banner GetDefaultComponentBanner();

	internal void Create(MobileParty party)
	{
		MobileParty = party;
		OnMobilePartySetOnCreation();
	}

	internal void Initialize(MobileParty party)
	{
		MobileParty = party;
		OnInitialize();
	}

	internal void Finish()
	{
		OnFinalize();
	}

	protected virtual void OnMobilePartySetOnCreation()
	{
	}

	protected virtual void OnInitialize()
	{
	}

	protected virtual void OnFinalize()
	{
	}

	public virtual void ClearCachedName()
	{
	}

	public void ChangePartyLeader(Hero newLeader)
	{
		if (newLeader != null && !MobileParty.MemberRoster.Contains(newLeader.CharacterObject))
		{
			Debug.FailedAssert(string.Concat(newLeader?.Name, " is not a member of ", Name, "!\nParty leader did not change."), "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "ChangePartyLeader", 67);
			return;
		}
		Hero leader = Leader;
		OnChangePartyLeader(newLeader);
		if (newLeader == null && MobileParty.MapEvent == null)
		{
			MobileParty.SetMoveModeHold();
		}
		if (leader != Leader)
		{
			CampaignEventDispatcher.Instance.OnPartyLeaderChanged(MobileParty, leader);
		}
	}

	protected virtual void OnChangePartyLeader(Hero newLeader)
	{
	}

	public virtual void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
	{
		mountStringId = "";
		harnessStringId = "";
	}
}
You are not using the latest version of the tool, please update.
Latest version is '11.0.0.9375' (yours is '8.2.0.7535-95108c96')
